### ISSUE TITLE
Feature Request: Reset Accessory

### ISSUE THREAD

**Issue by adrum** [rednblkx/HAP-ESPHome#10]
HomeKit has this feature where if a device changes any of its attributes, it can update an internal version number and paired devices will refresh the accessory configuration. This is helpful where you want to add new features by flashing different firmware, but don't want to unpair/pair the device all over again. This might be nice to implemented alongside #9 or any other configuration changes made.

https://github.com/ikalchev/HAP-python/blob/dev/pyhap/state.py

https://github.com/home-assistant/core/blob/dev/homeassistant/components/homekit/__init__.py#L714

**Comment by rednblkx** [comment]
There's no features to be modified at the moment besides homekey for lock entities, regardless, afaik the homekit library is already handling this.
