### ISSUE TITLE
I am getting the HKAuthCtx: authenticate > Response not valid, something went wrong! error when I place the phone with homekey turned on, close to the sensor.

### ISSUE THREAD

**Issue by EDENbys** [rednblkx/HAP-ESPHome#16]
my esp is nodemcu ESP32-S , I have not made any changes to the server that the esp32 creates, I only gave the wifi info and set the auth key 11122333 
I did not connect it to any mqtt broker service because I am trying to learn, whatever I do in the home app it says no response on the device. even if I try to make a simple led turn on with homespan. 

**the error message I get when I approach the phone**

(249634) MAIN: nfc_thread_entry > *** PASSIVE TARGET DETECTED ***[0m
(249847) HKAuthCtx: HKAuthenticationContext > Initialization Time: 185 ms[0m
(249905) HKAuthCtx: authenticate > Response not valid, something went wrong![0m
(249906) MAIN: nfc_thread_entry > We got status FlowFailed, mqtt untouched![0m
(250604) MAIN: nfc_thread_entry > *** PASSIVE TARGET DETECTED ***[0m
(261522) HKAuthCtx: HKAuthenticationContext > Initialization Time: 184 ms[0m
(261733) PN532: Status code indicates an error

**Comment by rednblkx** [comment]
Please note that this is the repository for HAP-ESPHome.
If you have an issue with [HomeKey-ESP32](https://github.com/rednblkx/HomeKey-ESP32), please open an issue on its respective repository.
