### ISSUE TITLE
Error Compiling before flashing.

### ISSUE THREAD

**Issue by mannyd209** [rednblkx/HAP-ESPHome#22]
Here is my compiling log with the error:

INFO ESPHome 2024.11.1
INFO Reading configuration /config/esphome/gen-controller.yaml...
INFO Updating https://github.com/rednblkx/HAP-ESPHome.git@main
INFO Generating C++ source...
INFO Updating https://github.com/espressif/idf-extra-components.git@master
INFO Updating submodules (libsodium/libsodium) for https://github.com/espressif/idf-extra-components.git@master
INFO Updating https://github.com/rednblkx/esp-homekit-sdk@master
INFO Compiling app...
Processing gen-controller (board: esp32dev; framework: espidf; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40408.0 (4.4.8) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
Dependency Graph
|-- noise-c @ 0.1.6
Compiling .pioenvs/gen-controller/src/esphome/components/homekit/HAPAccessory.o
Compiling .pioenvs/gen-controller/src/esphome/components/homekit/lock.o
Compiling .pioenvs/gen-controller/src/esphome/components/homekit_base/HAPRootComponent.o
src/esphome/components/homekit_base/HAPRootComponent.cpp: In constructor 'esphome::homekit::HAPRootComponent::HAPRootComponent(const char*, const char*, std::map<esphome::homekit::AInfo, const char*>)':
src/esphome/components/homekit_base/HAPRootComponent.cpp:27:25: error: 'class std::map<esphome::homekit::AInfo, const char*>' has no member named 'merge'
             merged_info.merge(info);
                         ^~~~~
src/esphome/components/homekit_base/HAPRootComponent.cpp:28:25: error: 'class std::map<esphome::homekit::AInfo, const char*>' has no member named 'merge'
             merged_info.merge(this->accessory_info);
                         ^~~~~
src/esphome/components/homekit_base/HAPRootComponent.cpp:52:13: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
             };
             ^
src/esphome/components/homekit_base/HAPRootComponent.cpp:52:13: warning: missing initializer for member 'hap_acc_cfg_t::hw_finish' [-Wmissing-field-initializers]
src/esphome/components/homekit_base/HAPRootComponent.cpp:52:13: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
In file included from src/esphome/components/homekit/HAPAccessory.h:14,
                 from src/esphome/components/homekit/HAPAccessory.cpp:1:
src/esphome/components/homekit/switch.hpp:17:12: error: 'map' in namespace 'std' does not name a template type
       std::map<AInfo, const char*> accessory_info = {{NAME, NULL}, {MODEL, "HAP-SWITCH"}, {SN, NULL}, {MANUFACTURER, "rednblkx"}, {FW_REV, "0.1"}};
            ^~~
src/esphome/components/homekit/switch.hpp:17:7: note: 'std::map' is defined in header '<map>'; did you forget to '#include <map>'?
src/esphome/components/homekit/switch.hpp:8:1:
+#include <map>
 
src/esphome/components/homekit/switch.hpp:17:7:
       std::map<AInfo, const char*> accessory_info = {{NAME, NULL}, {MODEL, "HAP-SWITCH"}, {SN, NULL}, {MANUFACTURER, "rednblkx"}, {FW_REV, "0.1"}};
       ^~~
In file included from src/esphome/components/homekit/HAPAccessory.h:14,
                 from src/esphome/components/homekit/HAPAccessory.cpp:1:
src/esphome/components/homekit/switch.hpp:56:25: error: 'std::map' has not been declared
       void setInfo(std::map<AInfo, const char*> info) {
                         ^~~
src/esphome/components/homekit/switch.hpp:56:28: error: expected ',' or '...' before '<' token
       void setInfo(std::map<AInfo, const char*> info) {
                            ^
src/esphome/components/homekit/switch.hpp: In member function 'void esphome::homekit::SwitchEntity::setInfo(int)':
src/esphome/components/homekit/switch.hpp:57:14: error: 'map' is not a member of 'std'
         std::map<AInfo, const char*> merged_info;
              ^~~
src/esphome/components/homekit/switch.hpp:57:14: note: 'std::map' is defined in header '<map>'; did you forget to '#include <map>'?
src/esphome/components/homekit/switch.hpp:57:23: error: expected primary-expression before ',' token
         std::map<AInfo, const char*> merged_info;
                       ^
src/esphome/components/homekit/switch.hpp:57:25: error: expected primary-expression before 'const'
         std::map<AInfo, const char*> merged_info;
                         ^~~~~
src/esphome/components/homekit/switch.hpp:58:9: error: 'merged_info' was not declared in this scope
         merged_info.merge(info);
         ^~~~~~~~~~~
src/esphome/components/homekit/switch.hpp:58:27: error: 'info' was not declared in this scope
         merged_info.merge(info);
                           ^~~~
src/esphome/components/homekit/switch.hpp:58:27: note: suggested alternative: 'AInfo'
         merged_info.merge(info);
                           ^~~~
                           AInfo
src/esphome/components/homekit/switch.hpp:59:33: error: 'class esphome::homekit::SwitchEntity' has no member named 'accessory_info'
         merged_info.merge(this->accessory_info);
                                 ^~~~~~~~~~~~~~
src/esphome/components/homekit/switch.hpp:60:15: error: 'class esphome::homekit::SwitchEntity' has no member named 'accessory_info'
         this->accessory_info.swap(merged_info);
               ^~~~~~~~~~~~~~
src/esphome/components/homekit/switch.hpp: In member function 'void esphome::homekit::SwitchEntity::setup()':
src/esphome/components/homekit/switch.hpp:64:29: error: 'accessory_info' was not declared in this scope
             .model = strdup(accessory_info[MODEL]),
                             ^~~~~~~~~~~~~~
src/esphome/components/homekit/switch.hpp:64:29: note: suggested alternative: 'is_accessory_paired'
             .model = strdup(accessory_info[MODEL]),
                             ^~~~~~~~~~~~~~
                             is_accessory_paired
*** [.pioenvs/gen-controller/src/esphome/components/homekit_base/HAPRootComponent.o] Error 1
*** [.pioenvs/gen-controller/src/esphome/components/homekit/HAPAccessory.o] Error 1
========================= [FAILED] Took 15.14 seconds =========================

Here is my config.yaml code: (I removed any personal passwords and info)

esphome:
  name: gen-controller
  platformio_options:
    board_build.flash_mode: dio

wifi:
  ssid: "" 
  password: ""
  ap:
    ssid: ""
    password: ""

# Captive Portal for fallback AP
captive_portal:

api:
  encryption:
    key: ""

ota:
  platform: esphome
  password: ""

logger:
  level: INFO

# External components for HomeKit
external_components:
  source: github://rednblkx/HAP-ESPHome@main
  refresh: 0s

esp32:
  board: esp32dev
  flash_size: 4MB
  framework:
    type: esp-idf

homekit_base:
  setup_code: '123-45-678'

homekit:
  switch:
    - id: generator_power_switch
      meta:
        manufacturer: "WingItOnWheels"
        model: "GENERATOR"
        serial_number: "123456789"
        fw_rev: "1.0.0"
    - id: generator_choke_switch
      meta:
        manufacturer: "WingItOnWheels"
        model: "GENERATOR"
        serial_number: "123456789"
        fw_rev: "1.0.0"
    - id: generator_start_switch
      meta:
        manufacturer: "WingItOnWheels"
        model: "GENERATOR"
        serial_number: "123456789"
        fw_rev: "1.0.0"
    - id: transfer_switch
      meta:
        manufacturer: "WingItOnWheels"
        model: "GENERATOR"
        serial_number: "123456789"
        fw_rev: "1.0.0"

binary_sensor:
  - platform: gpio
    id: generator_running
    pin:
      number: GPIO33
      mode: INPUT
    filters:
      - delayed_on_off:
          seconds: 3
    name: "Generator Running Status"
    device_class: power

  - platform: gpio
    id: grid_power_monitor
    pin:
      number: GPIO32
      mode: INPUT
    filters:
      - delayed_on_off:
          seconds: 3
    name: "Grid Power Status"
    device_class: power

switch:
  - platform: template
    id: generator_power_switch
    name: "Generator Power"
    restore_mode: RESTORE_DEFAULT_OFF
    lambda: |-
      if (id(generator_running).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - switch.turn_on: generator_power_switch
    turn_off_action:
      - switch.turn_off: generator_power_switch

  - platform: template
    id: generator_choke_switch
    name: "Generator Choke"
    restore_mode: RESTORE_DEFAULT_OFF
    lambda: |-
      if (id(generator_running).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - switch.turn_on: generator_choke_switch
    turn_off_action:
      - switch.turn_off: generator_choke_switch

  - platform: template
    id: generator_start_switch
    name: "Generator Start"
    restore_mode: RESTORE_DEFAULT_OFF
    lambda: |-
      if (id(generator_running).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - switch.turn_on: generator_start_switch
    turn_off_action:
      - switch.turn_off: generator_start_switch

  - platform: template
    id: transfer_switch
    name: "Transfer Switch"
    restore_mode: RESTORE_DEFAULT_OFF
    lambda: |-
      if (id(grid_power_monitor).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - switch.turn_on: transfer_switch
    turn_off_action:
      - switch.turn_off: transfer_switch

**Comment by rednblkx** [comment]
Hi!

Please note that only esp-idf version 5 is supported as indicated by the README. 

Reason for the error is a mismatch of c++ standards because esphome uses esp-idf version 4 as default (which is EoL btw) that uses C++11 as default while the code uses C++17 features as esp-idf 5 migrated to using c++23 as default.

This won't be fixed, suggest to adapt the config to use esp-idf 5 as mentioned in [Essentials](https://github.com/rednblkx/HAP-ESPHome?tab=readme-ov-file#2-essentials)

Also, for future references, please enclose logs and configuration in triple-backticks (` ``` `) for better readability.
