### ISSUE TITLE
Feature Request: Customizable Accessory Information

### ISSUE THREAD

**Issue by adrum** [rednblkx/HAP-ESPHome#9]
It would be nice to be able to customize the Accessory Information attributes for both the Bridge Accessory, and the Child Accessories, such as:

- Manufacturer
- Serial Number
- Model
- Firmware Version

**Comment by adrum** [comment]
Additionally, it might be nice to be able to customize the default bridge accessory name as well.

**Comment by rednblkx** [comment]
I'll keep that mind, thanks

**Comment by rednblkx** [comment]
The accessory information can now be modified for both the bridge and each individual accessory, see [documentation](https://github.com/rednblkx/HAP-ESPHome?tab=readme-ov-file#3-components)

I'll be closing this now, let me know if anything else, you can join the discord server if you wish https://discordapp.com/invite/VWpZ5YyUcm
